local c = require('darkplus.colors')

local theme = {}

theme.highlights = {
  Normal = { fg = c.fg, bg = c.bg },
  SignColumn = { fg = 'NONE', bg = c.bg },
  MsgArea = { fg = c.fg, bg = c.bg },
  ModeMsg = { fg = c.fg, bg = c.alt_bg },
  MsgSeparator = { fg = c.fg, bg = c.bg },
  SpellBad = { fg = 'NONE', bg = 'NONE', sp = c.red, undercurl = true, },
  SpellCap = { fg = 'NONE', bg = 'NONE', sp = c.yellow, undercurl = true, },
  SpellLocal = { fg = 'NONE', bg = 'NONE', sp = c.green, underline = true, },
  SpellRare = { fg = 'NONE', bg = 'NONE', sp = c.purple, underline = true, },
  NormalNC = { fg = c.fg, bg = c.bg },
  Pmenu = { fg = c.light_gray, bg = c.menu_bg },
  PmenuSel = { fg = 'NONE', bg = c.ui2_blue },
  WildMenu = { fg = c.fg, bg = c.ui2_blue },
  CursorLineNr = { fg = c.light_gray, bg = 'NONE' },
  Folded = { fg = c.gray, bg = c.alt_bg },
  FoldColumn = { fg = c.gray, bg = c.alt_bg },
  LineNr = { fg = c.gray, bg = 'NONE' },
  FloatBoder = { fg = c.gray, bg = c.alt_bg },
  Whitespace = { fg = c.bg, bg = 'NONE' },
  VertSplit = { fg = c.gray, bg = c.bg },
  CursorLine = { fg = 'NONE', bg = c.alt_bg },
  CursorColumn = { fg = 'NONE', bg = c.alt_bg },
  ColorColumn = { fg = 'NONE', bg = c.alt_bg },
  NormalFloat = { fg = 'NONE', bg = c.alt_bg },
  Visual = { fg = 'NONE', bg = c.ui_blue },
  VisualNOS = { fg = 'NONE', bg = c.alt_bg },
  WarningMsg = { fg = c.ui_orange, bg = c.bg },
  DiffText = { fg = c.alt_bg, bg = c.sign_delete },
  DiffAdd = { fg = c.alt_bg, bg = c.sign_add },
  DiffChange = { fg = c.alt_bg, bg = c.sign_change, underline = true, },
  DiffDelete = { fg = c.alt_bg, bg = c.sign_delete },
  QuickFixLine = { fg = 'NONE', bg = c.ui2_blue },
  PmenuSbar = { fg = 'NONE', bg = c.alt_bg },
  PmenuThumb = { fg = 'NONE', bg = c.gray },
  MatchWord = { fg = 'NONE', bg = c.reference },
  MatchParen = { fg = c.hint, bg = c.reference },
  MatchWordCur = { fg = 'NONE', bg = c.reference },
  MatchParenCur = { fg = 'NONE', bg = c.reference },
  Cursor = { fg = c.cursor_fg, bg = c.cursor_bg },
  lCursor = { fg = c.cursor_fg, bg = c.cursor_bg },
  CursorIM = { fg = c.cursor_fg, bg = c.cursor_bg },
  TermCursor = { fg = c.cursor_fg, bg = c.cursor_bg },
  TermCursorNC = { fg = c.cursor_fg, bg = c.cursor_bg },
  Conceal = { fg = c.gray, bg = 'NONE' },
  Directory = { fg = c.folder_blue, bg = 'NONE' },
  SpecialKey = { fg = c.blue, bg = 'NONE', bold = true, },
  ErrorMsg = { fg = c.error, bg = c.bg, bold = true, },
  Search = { fg = 'NONE', bg = c.ui5_blue },
  IncSearch = { fg = 'NONE', bg = c.ui2_orange },
  Substitute = { fg = 'NONE', bg = c.ui2_orange },
  MoreMsg = { fg = c.orange, bg = 'NONE' },
  Question = { fg = c.orange, bg = 'NONE' },
  EndOfBuffer = { fg = c.bg, bg = 'NONE' },
  NonText = { fg = c.bg, bg = 'NONE' },
  TabLine = { fg = c.light_gray, bg = c.line },
  TabLineSel = { fg = c.fg, bg = c.line },
  TabLineFill = { fg = c.line, bg = c.line },

  -- Code
  Comment = { fg = c.context, bg = 'NONE' },
  Variable = { fg = c.light_blue, bg = 'NONE' },
  String = { fg = c.orange, bg = 'NONE' },
  Character = { fg = c.orange, bg = 'NONE' },
  Number = { fg = c.light_green, bg = 'NONE' },
  Float = { fg = c.light_green, bg = 'NONE' },
  Boolean = { fg = c.blue, bg = 'NONE' },
  Constant = { fg = c.vivid_blue, bg = 'NONE' },
  Type = { fg = c.cyan, bg = 'NONE' },
  Function = { fg = c.yellow, bg = 'NONE' },
  Keyword = { fg = c.blue, bg = 'NONE' },
  Conditional = { fg = c.purple, bg = 'NONE' },
  Repeat = { fg = c.purple, bg = 'NONE' },
  Operator = { fg = c.fg, bg = 'NONE' },
  PreProc = { fg = c.purple, bg = 'NONE' },
  Include = { fg = c.purple, bg = 'NONE' },
  Exception = { fg = c.purple, bg = 'NONE' },
  StorageClass = { fg = c.cyan, bg = 'NONE' },
  Structure = { fg = c.cyan, bg = 'NONE' },
  Typedef = { fg = c.purple, bg = 'NONE' },
  Define = { fg = c.purple, bg = 'NONE' },
  Macro = { fg = c.blue, bg = 'NONE' },
  Debug = { fg = c.red, bg = 'NONE' },
  Title = { fg = c.blue, bg = 'NONE', bold = true, },
  Label = { fg = c.blue, bg = 'NONE' },
  SpecialChar = { fg = c.orange, bg = 'NONE' },
  Delimiter = { fg = c.fg, bg = 'NONE' },
  SpecialComment = { fg = c.fg, bg = 'NONE' },
  Tag = { fg = c.blue, bg = 'NONE' },
  Bold = { fg = 'NONE', bg = 'NONE', bold = true, },
  Italic = { fg = 'NONE', bg = 'NONE', italic = true, },
  Underlined = { fg = 'NONE', bg = 'NONE', underline = true, },
  Ignore = { fg = c.magenta, bg = 'NONE', bold = true, },
  Todo = { fg = c.magenta, bg = 'NONE', bold = true, },
  Error = { fg = c.error, bg = 'NONE', bold = true, },
  Statement = { fg = c.purple, bg = 'NONE' },
  Identifier = { fg = c.fg, bg = 'NONE' },
  PreCondit = { fg = c.purple, bg = 'NONE' },
  Special = { fg = c.orange, bg = 'NONE' },

  -- Treesitter
  TSComment = { fg = c.context, bg = 'NONE', italic = true, },
  TSVariable = { link = 'Variable' },
  TSString = { link = 'String' },
  TSStringRegex = { link = 'String' },
  TSStringEscape = { link = 'String' },
  TSCharacter = { link = 'String' },
  TSCharacterSpecial = { link = 'SpecialChar' },
  TSNumber = { link = 'Number' },
  TSFloat = { link = 'Float' },
  TSBoolean = { link = 'Boolean' },
  TSConstant = { link = 'Constant' },
  TSConstBuiltin = { link = 'Constant' },
  TSConstructor = { link = 'Type' },
  TSType = { link = 'Type' },
  TSInclude = { link = 'Include' },
  TSException = { link = 'Exception' },
  TSKeyword = { link = 'Keyword' },
  TSKeywordReturn = { link = 'Include' },
  TSKeywordOperator = { link = 'Include' },
  TSKeywordFunction = { link = 'Keyword' },
  TSFunction = { link = 'Function' },
  TSFuncBuiltin = { link = 'Type' },
  TSMethod = { link = 'Function' },
  TSFuncMacro = { link = 'Function' },
  TSConditional = { link = 'Conditional' },
  TSRepeat = { link = 'Repeat' },
  TSOperator = { link = 'Operator' },
  TSPreProc = { link = 'PreProc' },
  TSStorageClass = { link = 'StorageClass' },
  TSStructure = { link = 'Structure' },
  TSTypeDefinition = { link = 'Typedef' },
  TSDefine = { link = 'Define' },
  TSNote = { link = 'Comment' },
  TSTodo = { link = 'Todo' },
  TSDebug = { link = 'Debug' },
  TSDanger = { link = 'Error' },
  TSTitle = { link = 'Title' },
  TSLabel = { link = 'Label' },
  TSPunctDelimiter = { link = 'Delimiter' },
  TSTagDelimiter = { fg = c.gray, bg = 'NONE' },
  TSPunctBracket = { link = 'Delimiter' },
  TSPunctSpecial = { link = 'Delimiter' },
  TSTag = { link = 'Tag' },
  TSStrong = { link = 'Bold' },
  TSEmphasis = { link = 'Italic' },
  TSUnderline = { link = 'Underline' },
  TSStrike = { fg = 'NONE', bg = 'NONE', strikethrough = true, },
  TSStringSpecial = { fg = c.fg, bg = 'NONE' },
  TSEnvironmentName = { fg = c.cyan, bg = 'NONE' },
  TSVariableBuiltin = { fg = c.cyan, bg = 'NONE' },
  TSConstMacro = { fg = c.vivid_blue, bg = 'NONE' },
  TSTypeBuiltin = { fg = c.cyan, bg = 'NONE' },
  TSAnnotation = { fg = c.blue, bg = 'NONE' },
  TSNamespace = { fg = c.cyan, bg = 'NONE' },
  TSSymbol = { fg = c.fg, bg = 'NONE' },
  TSField = { link = 'Variable' },
  TSProperty = { fg = c.light_blue, bg = 'NONE' },
  TSParameter = { fg = c.light_blue, bg = 'NONE' },
  TSParameterReference = { fg = c.light_blue, bg = 'NONE' },
  TSAttribute = { fg = c.cyan, bg = 'NONE' },
  TSText = { fg = c.fg, bg = 'NONE' },
  TSTagAttribute = { fg = c.light_blue, bg = 'NONE', italic = true, },
  TSError = { fg = c.error, bg = 'NONE' },
  TSWarning = { fg = c.warn, bg = 'NONE' },
  TSQueryLinterError = { fg = c.error, bg = 'NONE' },
  TSURI = { fg = c.cyan, bg = 'NONE', underline = true, },
  TSMath = { fg = c.yellow, bg = 'NONE' },
  TSLiteral = { fg = c.orange, bg = 'NONE' },

  -- markdown
  markdownBlockquote = { fg = c.orange, bg = 'NONE' },
  markdownCode = { fg = c.orange, bg = 'NONE' },
  markdownCodeBlock = { fg = c.orange, bg = 'NONE' },
  markdownCodeDelimiter = { fg = c.orange, bg = 'NONE' },
  markdownH1 = { link = 'Title' },
  markdownH2 = { link = 'Title' },
  markdownH3 = { link = 'Title' },
  markdownH4 = { link = 'Title' },
  markdownH5 = { link = 'Title' },
  markdownH6 = { link = 'Title' },
  markdownHeadingDelimiter = { fg = c.blue, bg = 'NONE' },
  markdownHeadingRule = { fg = c.fg, bg = 'NONE', bold = true, },
  markdownId = { link = 'Identifier' },
  markdownIdDeclaration = { fg = c.blue, bg = 'NONE' },
  markdownIdDelimiter = { fg = c.light_gray, bg = 'NONE' },
  markdownLinkDelimiter = { fg = c.light_gray, bg = 'NONE' },
  markdownBold = { fg = c.blue, bg = 'NONE', bold = true, },
  markdownItalic = { link = 'Italic' },
  markdownBoldItalic = { fg = c.yellow, bg = 'NONE', bold = true, italic = true, },
  markdownListMarker = { fg = c.blue, bg = 'NONE' },
  markdownOrderedListMarker = { fg = c.purple, bg = 'NONE' },
  markdownRule = { fg = c.gray, bg = 'NONE' },
  markdownUrl = { fg = c.cyan, bg = 'NONE', underdotted = true, },
  markdownLinkText = { fg = c.blue, bg = 'NONE' },
  markdownFootnote = { fg = c.orange, bg = 'NONE' },
  markdownFootnoteDefinition = { fg = c.orange, bg = 'NONE' },
  markdownEscape = { fg = c.yellow, bg = 'NONE' },

  -- Whichkey
  WhichKey = { fg = c.purple, bg = 'NONE' },
  WhichKeySeperator = { fg = c.green, bg = 'NONE' },
  WhichKeyGroup = { fg = c.blue, bg = 'NONE' },
  WhichKeyDesc = { fg = c.fg, bg = 'NONE' },
  WhichKeyFloat = { fg = 'NONE', bg = c.alt_bg },

  -- Git
  SignAdd = { fg = c.sign_add, bg = 'NONE' },
  SignChange = { fg = c.sign_change, bg = 'NONE' },
  SignDelete = { fg = c.sign_delete, bg = 'NONE' },
  GitSignsAdd = { fg = c.sign_add, bg = 'NONE' },
  GitSignsChange = { fg = c.sign_change, bg = 'NONE' },
  GitSignsDelete = { fg = c.sign_delete, bg = 'NONE' },

  -- LSP
  DiagnosticHint = { fg = c.hint, bg = 'NONE' },
  DiagnosticInfo = { fg = c.info, bg = 'NONE' },
  DiagnosticWarn = { fg = c.warn, bg = 'NONE' },
  DiagnosticError = { fg = c.error, bg = 'NONE' },
  DiagnosticOther = { fg = c.ui_purple, bg = 'NONE' },
  DiagnosticSignHint = { link = 'DiagnosticHint' },
  DiagnosticSignInfo = { link = 'DiagnosticInfo' },
  DiagnosticSignWarn = { link = 'DiagnosticWarn' },
  DiagnosticSignError = { link = 'DiagnosticError' },
  DiagnosticSignOther = { link = 'DiagnosticOther' },
  DiagnosticSignWarning = { link = 'DiagnosticWarn' },
  DiagnosticFloatingHint = { link = 'DiagnosticHint' },
  DiagnosticFloatingInfo = { link = 'DiagnosticInfo' },
  DiagnosticFloatingWarn = { link = 'DiagnosticWarn' },
  DiagnosticFloatingError = { link = 'DiagnosticError' },
  DiagnosticUnderlineHint = { fg = 'NONE', bg = 'NONE', sp = c.hint, undercurl = true, },
  DiagnosticUnderlineInfo = { fg = 'NONE', bg = 'NONE', sp = c.info, undercurl = true, },
  DiagnosticUnderlineWarn = { fg = 'NONE', bg = 'NONE', sp = c.warn, undercurl = true, },
  DiagnosticUnderlineError = { fg = 'NONE', bg = 'NONE', sp = c.error, undercurl = true, },
  DiagnosticSignInformation = { link = 'DiagnosticInfo' },
  DiagnosticVirtualTextHint = { fg = c.hint, bg = c.hint_bg },
  DiagnosticVirtualTextInfo = { fg = c.info, bg = c.info_bg },
  DiagnosticVirtualTextWarn = { fg = c.warn, bg = c.warn_bg },
  DiagnosticVirtualTextError = { fg = c.error, bg = c.error_bg },
  LspDiagnosticsError = { fg = c.error, bg = 'NONE' },
  LspDiagnosticsWarning = { fg = c.warn, bg = 'NONE' },
  LspDiagnosticsInfo = { fg = c.info, bg = 'NONE' },
  LspDiagnosticsInformation = { link = 'LspDiagnosticsInfo' },
  LspDiagnosticsHint = { fg = c.hint, bg = 'NONE' },
  LspDiagnosticsDefaultError = { link = 'LspDiagnosticsError' },
  LspDiagnosticsDefaultWarning = { link = 'LspDiagnosticsWarning' },
  LspDiagnosticsDefaultInformation = { link = 'LspDiagnosticsInfo' },
  LspDiagnosticsDefaultInfo = { link = 'LspDiagnosticsInfo' },
  LspDiagnosticsDefaultHint = { link = 'LspDiagnosticsHint' },
  LspDiagnosticsVirtualTextError = { link = 'DiagnosticVirtualTextError' },
  LspDiagnosticsVirtualTextWarning = { link = 'DiagnosticVirtualTextWarn' },
  LspDiagnosticsVirtualTextInformation = { link = 'DiagnosticVirtualTextInfo' },
  LspDiagnosticsVirtualTextInfo = { link = 'DiagnosticVirtualTextInfo' },
  LspDiagnosticsVirtualTextHint = { link = 'DiagnosticVirtualTextHint' },
  LspDiagnosticsFloatingError = { link = 'LspDiagnosticsError' },
  LspDiagnosticsFloatingWarning = { link = 'LspDiagnosticsWarning' },
  LspDiagnosticsFloatingInformation = { link = 'LspDiagnosticsInfo' },
  LspDiagnosticsFloatingInfo = { link = 'LspDiagnosticsInfo' },
  LspDiagnosticsFloatingHint = { link = 'LspDiagnosticsHint' },
  LspDiagnosticsSignError = { link = 'LspDiagnosticsError' },
  LspDiagnosticsSignWarning = { link = 'LspDiagnosticsWarning' },
  LspDiagnosticsSignInformation = { link = 'LspDiagnosticsInfo' },
  LspDiagnosticsSignInfo = { link = 'LspDiagnosticsInfo' },
  LspDiagnosticsSignHint = { link = 'LspDiagnosticsHint' },
  NvimTreeLspDiagnosticsError = { link = 'LspDiagnosticsError' },
  NvimTreeLspDiagnosticsWarning = { link = 'LspDiagnosticsWarning' },
  NvimTreeLspDiagnosticsInformation = { link = 'LspDiagnosticsInfo' },
  NvimTreeLspDiagnosticsInfo = { link = 'LspDiagnosticsInfo' },
  NvimTreeLspDiagnosticsHint = { link = 'LspDiagnosticsHint' },
  LspDiagnosticsUnderlineError = { link = 'DiagnosticUnderlineError' },
  LspDiagnosticsUnderlineWarning = { link = 'DiagnosticUnderlineWarn' },
  LspDiagnosticsUnderlineInformation = { link = 'DiagnosticUnderlineInfo' },
  LspDiagnosticsUnderlineInfo = { link = 'DiagnosticUnderlineInfo' },
  LspDiagnosticsUnderlineHint = { link = 'DiagnosticUnderlineHint' },
  LspReferenceRead = { fg = 'NONE', bg = c.reference },
  LspReferenceText = { fg = 'NONE', bg = c.reference },
  LspReferenceWrite = { fg = 'NONE', bg = c.reference },
  IlluminatedWordRead = { link = 'LspReferenceRead' },
  IlluminatedWordText = { link = 'LspReferenceText' },
  IlluminatedWordWrite = { link = 'LspReferenceWrite' },
  LspCodeLens = { fg = c.context, bg = 'NONE', italic = true, },
  LspCodeLensSeparator = { fg = c.context, bg = 'NONE', italic = true, },

  -- Quickscope
  QuickScopePrimary = { fg = '#ff007c', bg = 'NONE', underline = true, },
  QuickScopeSecondary = { fg = '#00dfff', bg = 'NONE', underline = true, },

  -- Telescope
  TelescopeSelection = { fg = 'NONE', bg = c.ui2_blue },
  TelescopeSelectionCaret = { fg = c.red, bg = c.ui2_blue },
  TelescopeMatching = { fg = c.info, bg = 'NONE', bold = true, italic = true, },
  TelescopeBorder = { fg = c.alt_fg, bg = 'NONE' },
  TelescopeNormal = { fg = c.fg, bg = c.menu_bg },
  TelescopePromptPrefix = { fg = c.hint, bg = 'NONE' },
  TelescopePromptTitle = { fg = c.ui_orange, bg = 'NONE', bold = true, },
  TelescopeResultsTitle = { fg = c.ui_orange, bg = 'NONE', bold = true, },
  TelescopePreviewTitle = { fg = c.ui_orange, bg = 'NONE', bold = true, },
  TelescopePromptCounter = { fg = c.red, bg = 'NONE' },
  TelescopePreviewHyphen = { fg = c.red, bg = 'NONE' },

  -- NvimTree
  NvimTreeFolderIcon = { link = 'Directory' },
  NvimTreeIndentMarker = { fg = c.context, bg = 'NONE' },
  NvimTreeNormal = { fg = c.fg, bg = c.alt_bg },
  NvimTreeVertSplit = { fg = c.alt_bg, bg = c.alt_bg },
  NvimTreeFolderName = { link = 'Directory' },
  NvimTreeOpenedFolderName = { fg = c.folder_blue, bg = 'NONE', bold = true, italic = true, },
  NvimTreeEmptyFolderName = { fg = c.gray, bg = 'NONE', italic = true, },
  NvimTreeGitIgnored = { fg = c.gray, bg = 'NONE', italic = true, },
  NvimTreeImageFile = { fg = c.light_gray, bg = 'NONE' },
  NvimTreeSpecialFile = { fg = c.orange, bg = 'NONE' },
  NvimTreeEndOfBuffer = { fg = c.alt_bg, bg = 'NONE' },
  NvimTreeCursorLine = { fg = 'NONE', bg = c.line },
  NvimTreeGitStaged = { fg = c.sign_add_alt, bg = 'NONE' },
  NvimTreeGitNew = { fg = c.sign_add_alt, bg = 'NONE' },
  NvimTreeGitRenamed = { fg = c.sign_add_alt, bg = 'NONE' },
  NvimTreeGitDeleted = { fg = c.sign_delete, bg = 'NONE' },
  NvimTreeGitMerge = { fg = c.sign_change_alt, bg = 'NONE' },
  NvimTreeGitDirty = { fg = c.sign_change_alt, bg = 'NONE' },
  NvimTreeSymlink = { fg = c.cyan, bg = 'NONE' },
  NvimTreeRootFolder = { fg = c.fg, bg = 'NONE', bold = true, },
  NvimTreeExecFile = { fg = '#9FBA89', bg = 'NONE' },

  -- Lir
  LirFloatNormal = { fg = c.fg, bg = c.alt_bg },
  LirDir = { link = 'Directory' },
  LirSymLink = { fg = c.cyan, bg = 'NONE' },
  LirEmptyDirText = { fg = c.gray, bg = 'NONE', italic = true, },

  -- Buffer
  BufferCurrent = { fg = c.fg, bg = c.bg },
  BufferCurrentIndex = { fg = c.fg, bg = c.bg },
  BufferCurrentMod = { fg = c.info, bg = c.bg },
  BufferCurrentSign = { fg = c.hint, bg = c.bg },
  BufferCurrentTarget = { fg = c.red, bg = c.bg, bold = true, },
  BufferVisible = { fg = c.fg, bg = c.bg },
  BufferVisibleIndex = { fg = c.fg, bg = c.bg },
  BufferVisibleMod = { fg = c.info, bg = c.bg },
  BufferVisibleSign = { fg = c.gray, bg = c.bg },
  BufferVisibleTarget = { fg = c.red, bg = c.bg, bold = true, },
  BufferInactive = { fg = c.gray, bg = c.alt_bg },
  BufferInactiveIndex = { fg = c.gray, bg = c.alt_bg },
  BufferInactiveMod = { fg = c.info, bg = c.alt_bg },
  BufferInactiveSign = { fg = c.gray, bg = c.alt_bg },
  BufferInactiveTarget = { fg = c.red, bg = c.alt_bg, bold = true, },

  -- StatusLine
  StatusLine = { fg = c.context, bg = c.bg },
  StatusLineNC = { fg = c.line, bg = c.bg },
  StatusLineSeparator = { fg = c.line, bg = 'NONE' },
  StatusLineTerm = { fg = c.line, bg = 'NONE' },
  StatusLineTermNC = { fg = c.line, bg = 'NONE' },

  -- IndentBlankline
  IndentBlanklineContextChar = { fg = c.context, bg = 'NONE' },
  IndentBlanklineContextStart = { fg = 'NONE', bg = 'NONE', underline = true, },
  IndentBlanklineChar = { fg = c.dark_gray, bg = 'NONE' },

  -- Dashboard
  DashboardHeader = { fg = c.blue, bg = 'NONE' },
  DashboardCenter = { fg = c.purple, bg = 'NONE' },
  DashboardFooter = { fg = c.cyan, bg = 'NONE' },

  -- DiffView
  DiffViewNormal = { fg = c.gray, bg = c.alt_bg },
  DiffviewStatusAdded = { fg = c.sign_add, bg = 'NONE' },
  DiffviewStatusModified = { fg = c.sign_change, bg = 'NONE' },
  DiffviewStatusRenamed = { fg = c.sign_change, bg = 'NONE' },
  DiffviewStatusDeleted = { fg = c.sign_delete, bg = 'NONE' },
  DiffviewFilePanelInsertion = { fg = c.sign_add, bg = 'NONE' },
  DiffviewFilePanelDeletion = { fg = c.sign_delete, bg = 'NONE' },
  DiffviewVertSplit = { fg = 'NONE', bg = c.bg },

  -- Bookmarks
  BookmarkSign = { fg = c.sign_change, bg = 'NONE' },
  BookmarkAnnotationSign = { fg = c.yellow, bg = 'NONE' },
  BookmarkLine = { fg = c.ui2_blue, bg = 'NONE' },
  BookmarkAnnotationLine = { fg = c.ui2_blue, bg = 'NONE' },

  -- Bqf
  BqfPreviewBorder = { fg = c.fg, bg = 'NONE' },
  BqfPreviewRange = { fg = 'NONE', bg = c.ui2_blue },

  -- Cmp
  CmpItemAbbrDeprecated = { fg = c.gray, bg = 'NONE', strikethrough = true, },
  CmpItemAbbrMatch = { fg = c.ui3_blue, bg = 'NONE' },
  CmpItemAbbrMatchFuzzy = { fg = c.ui3_blue, bg = 'NONE' },
  CmpItemKindFunction = { fg = c.ui_purple, bg = 'NONE' },
  CmpItemKindMethod = { fg = c.ui_purple, bg = 'NONE' },
  CmpItemKindConstructor = { fg = c.ui_orange, bg = 'NONE' },
  CmpItemKindClass = { fg = c.ui_orange, bg = 'NONE' },
  CmpItemKindEnum = { fg = c.ui_orange, bg = 'NONE' },
  CmpItemKindEvent = { fg = c.info, bg = 'NONE' },
  CmpItemKindInterface = { fg = c.ui_orange, bg = 'NONE' },
  CmpItemKindStruct = { fg = c.ui_orange, bg = 'NONE' },
  CmpItemKindVariable = { fg = c.light_blue, bg = 'NONE' },
  CmpItemKindField = { fg = c.light_blue, bg = 'NONE' },
  CmpItemKindProperty = { fg = c.light_blue, bg = 'NONE' },
  CmpItemKindEnumMember = { fg = c.vivid_blue, bg = 'NONE' },
  CmpItemKindConstant = { fg = c.vivid_blue, bg = 'NONE' },
  CmpItemKindKeyword = { fg = c.fg, bg = 'NONE' },
  CmpItemKindModule = { fg = c.cyan, bg = 'NONE' },
  CmpItemKindValue = { fg = c.fg, bg = 'NONE' },
  CmpItemKindUnit = { fg = c.fg, bg = 'NONE' },
  CmpItemKindText = { fg = c.fg, bg = 'NONE' },
  CmpItemKindSnippet = { fg = c.fg, bg = 'NONE' },
  CmpItemKindFile = { fg = c.fg, bg = 'NONE' },
  CmpItemKindFolder = { fg = c.fg, bg = 'NONE' },
  CmpItemKindColor = { fg = c.fg, bg = 'NONE' },
  CmpItemKindReference = { fg = c.light_blue, bg = 'NONE' },
  CmpItemKindOperator = { fg = c.fg, bg = 'NONE' },
  CmpItemKindTypeParameter = { fg = c.light_blue, bg = 'NONE' },

  -- Navic
  NavicIconsFile = { link = 'CmpItemKindFile' },
  NavicIconsModule = { link = 'CmpItemKindModule' },
  NavicIconsNamespace = { link = 'CmpItemKindModule' },
  NavicIconsPackage = { link = 'CmpItemKindModule' },
  NavicIconsClass = { link = 'CmpItemKindClass' },
  NavicIconsMethod = { link = 'CmpItemKindMethod' },
  NavicIconsProperty = { link = 'CmpItemKindProperty' },
  NavicIconsField = { link = 'CmpItemKindField' },
  NavicIconsConstructor = { link = 'CmpItemKindConstructor' },
  NavicIconsEnum = { link = 'CmpItemKindEnum' },
  NavicIconsInterface = { link = 'CmpItemKindInterface' },
  NavicIconsFunction = { link = 'CmpItemKindFunction' },
  NavicIconsVariable = { link = 'CmpItemKindVariable' },
  NavicIconsConstant = { link = 'CmpItemKindConstant' },
  NavicIconsString = { link = 'String' },
  NavicIconsNumber = { link = 'Number' },
  NavicIconsBoolean = { link = 'Boolean' },
  NavicIconsArray = { link = 'CmpItemKindClass' },
  NavicIconsObject = { link = 'CmpItemKindClass' },
  NavicIconsKey = { link = 'CmpItemKindKeyword' },
  NavicIconsKeyword = { link = 'CmpItemKindKeyword' },
  NavicIconsNull = { fg = c.blue, bg = 'NONE' },
  NavicIconsEnumMember = { link = 'CmpItemKindEnumMember' },
  NavicIconsStruct = { link = 'CmpItemKindStruct' },
  NavicIconsEvent = { link = 'CmpItemKindEvent' },
  NavicIconsOperator = { link = 'CmpItemKindOperator' },
  NavicIconsTypeParameter = { link = 'CmpItemKindTypeParameter' },
  NavicText = { fg = c.gray, bg = 'NONE' },
  NavicSeparator = { fg = c.context, bg = 'NONE' },

  -- Packer
  packerString = { fg = c.ui_orange, bg = 'NONE' },
  packerHash = { fg = c.ui4_blue, bg = 'NONE' },
  packerOutput = { fg = c.ui_purple, bg = 'NONE' },
  packerRelDate = { fg = c.gray, bg = 'NONE' },
  packerSuccess = { fg = c.success_green, bg = 'NONE' },
  packerStatusSuccess = { fg = c.ui4_blue, bg = 'NONE' },

  -- SymbolOutline
  SymbolsOutlineConnector = { fg = c.gray, bg = 'NONE' },
  FocusedSymbol = { fg = 'NONE', bg = '#36383F' },

  -- Notify
  NotifyERRORBorder = { fg = '#8A1F1F', bg = 'NONE' },
  NotifyWARNBorder = { fg = '#79491D', bg = 'NONE' },
  NotifyINFOBorder = { fg = c.ui_blue, bg = 'NONE' },
  NotifyDEBUGBorder = { fg = c.gray, bg = 'NONE' },
  NotifyTRACEBorder = { fg = '#4F3552', bg = 'NONE' },
  NotifyERRORIcon = { fg = c.error, bg = 'NONE' },
  NotifyWARNIcon = { fg = c.warn, bg = 'NONE' },
  NotifyINFOIcon = { fg = c.ui4_blue, bg = 'NONE' },
  NotifyDEBUGIcon = { fg = c.gray, bg = 'NONE' },
  NotifyTRACEIcon = { fg = c.ui_purple, bg = 'NONE' },
  NotifyERRORTitle = { fg = c.error, bg = 'NONE' },
  NotifyWARNTitle = { fg = c.warn, bg = 'NONE' },
  NotifyINFOTitle = { fg = c.ui4_blue, bg = 'NONE' },
  NotifyDEBUGTitle = { fg = c.gray, bg = 'NONE' },
  NotifyTRACETitle = { fg = c.ui_purple, bg = 'NONE' },

  -- TreesitterContext
  TreesitterContext = { fg = 'NONE', bg = c.alt_bg },

  -- Hop
  HopNextKey = { fg = '#ff007c', bg = 'NONE' },
  HopNextKey1 = { fg = '#00dfff', bg = 'NONE' },
  HopNextKey2 = { fg = '#2b8db3', bg = 'NONE' },
  HopUnmatched = { fg = c.gray, bg = 'NONE' },
  HopCursor = { link = "Cursor" },
  HopPreview = { link = "IncSearch" },

  -- Crates
  CratesNvimLoading = { fg = c.hint, bg = 'NONE' },
  CratesNvimVersion = { fg = c.hint, bg = 'NONE' },

  -- Misc
  diffAdded = { fg = c.sign_add, bg = 'NONE' },
  diffRemoved = { fg = c.sign_delete, bg = 'NONE' },
  diffFileId = { fg = c.blue, bg = 'NONE', bold = true, reverse = true, },
  diffFile = { fg = c.alt_bg, bg = 'NONE' },
  diffNewFile = { fg = c.green, bg = 'NONE' },
  diffOldFile = { fg = c.red, bg = 'NONE' },
  debugPc = { fg = 'NONE', bg = c.ui5_blue },
  debugBreakpoint = { fg = c.red, bg = 'NONE', reverse = true, },
  CodiVirtualText = { fg = c.hint, bg = 'NONE' },
  SniprunVirtualTextOk = { fg = c.hint, bg = 'NONE' },
  SniprunFloatingWinOk = { fg = c.hint, bg = 'NONE' },
  SniprunVirtualTextErr = { fg = c.error, bg = 'NONE' },
  SniprunFloatingWinErr = { fg = c.error, bg = 'NONE' },
  DapBreakpoint = { fg = c.error, bg = 'NONE' },

  -- Language,
  xmlTag = { fg = c.cyan, bg = 'NONE' },
  xmlTagName = { fg = c.cyan, bg = 'NONE' },
  xmlEndTag = { fg = c.cyan, bg = 'NONE' },
  -- yamlPlainScalar = { fg = c.orange, bg = 'NONE' },
  -- yamlTSField = { fg = c.blue, bg = 'NONE' },
  luaFunc = { fg = c.yellow, bg = 'NONE' },
  luaFunction = { fg = c.blue, bg = 'NONE' },
  hclTSPunctSpecial = { fg = c.alt_fg, bg = 'NONE' },
  htmlH1 = { fg = c.fg, bg = 'NONE' },
  htmlH2 = { fg = c.fg, bg = 'NONE' },
  htmlH3 = { fg = c.fg, bg = 'NONE' },
  htmlH4 = { fg = c.fg, bg = 'NONE' },
  htmlH5 = { fg = c.fg, bg = 'NONE' },
  htmlH6 = { fg = c.fg, bg = 'NONE' },
  htmlHead = { fg = c.fg, bg = 'NONE' },
  htmlTitle = { fg = c.fg, bg = 'NONE' },
  htmlArg = { fg = c.fg, bg = 'NONE' },
  htmlTag = { fg = c.blue, bg = 'NONE' },
  htmlTagN = { fg = c.blue, bg = 'NONE' },
  htmlTagName = { fg = c.blue, bg = 'NONE' },
  htmlComment = { fg = c.green, bg = 'NONE' },
  htmlLink = { fg = c.orange, bg = 'NONE', underline = true, },
  cssBraces = { fg = c.fg, bg = 'NONE' },
  cssInclude = { fg = c.purple, bg = 'NONE' },
  cssTagName = { fg = c.yellow, bg = 'NONE' },
  cssClassName = { fg = c.yellow, bg = 'NONE' },
  cssPseudoClass = { fg = c.yellow, bg = 'NONE' },
  cssPseudoClassId = { fg = c.yellow, bg = 'NONE' },
  cssPseudoClassLang = { fg = c.yellow, bg = 'NONE' },
  cssIdentifier = { fg = c.yellow, bg = 'NONE' },
  cssProp = { fg = c.fg, bg = 'NONE' },
  cssDefinition = { fg = c.fg, bg = 'NONE' },
  cssAttr = { fg = c.orange, bg = 'NONE' },
  cssAttrRegion = { fg = c.orange, bg = 'NONE' },
  cssColor = { fg = c.orange, bg = 'NONE' },
  cssFunction = { fg = c.purple, bg = 'NONE' },
  cssFunctionName = { fg = c.yellow, bg = 'NONE' },
  cssVendor = { fg = c.orange, bg = 'NONE' },
  cssValueNumber = { fg = c.orange, bg = 'NONE' },
  cssValueLength = { fg = c.orange, bg = 'NONE' },
  cssUnitDecorators = { fg = c.orange, bg = 'NONE' },
  cssStyle = { fg = c.fg, bg = 'NONE' },
  cssImportant = { fg = c.blue, bg = 'NONE' },
  jsonKeyword = { fg = c.blue, bg = 'NONE' },
  yamlBlockMappingKey = { fg = c.blue, bg = 'NONE' },
  tomlTSProperty = { fg = c.blue, bg = 'NONE' },
}

return theme
