#!/bin/bash

choice=$(echo -e "Hibernate\nSleep\nSuspend\nShutdown\nReboot" | rofi -dmenu --width=200 --height=200 )

case "$choice" in
  Hibernate) systemctl hibernate ;;
  Sleep) systemctl sleep ;;
  Shutdown) systemctl poweroff ;;
  Reboot) systemctl reboot ;;
  Suspend) systemctl suspend ;;
esac
