[settings]
experimental = true
disable_hints = ["registry"]

[tools]
usage = "latest"
neovim = "latest"
cheat = "latest"
tmux = "3.4"
bun = "latest"
kubectl = "latest"
kubectl-convert = "latest"
helm = "latest"
terraform = "latest"
k9s = "latest"

[env]
