return {
  alpha = {
    File = "",
    FindFile = "",
    Folder = "",
    Settings = "",
    RecentlyUsed = "",
    Quit = "",
    Text = "",
    Telescope = "",
    SignIn = "",
    Reference = "",
    Checkhealth = "",
    Neorg = "",
  },
  Close = " ",
  Telescope = " ",
  --   פּ ﯟ   some other good icons
  -- find more here: https://www.nerdfonts.com/cheat-sheet
  kind_icons = {
    Array = " ",
    Boolean = " ",
    Class = "",
    Constant = "",
    Constructor = "",
    Enum = "",
    EnumMember = "",
    Event = "",
    Field = "",
    File = "",
    Function = "",
    Interface = "",
    Key = "",
    Method = "m",
    Module = "",
    Namespace = "ﰩ",
    Null = "n",
    Number = " ",
    Object = " ",
    Operator = "",
    Package = "",
    Property = "",
    String = " ",
    Struct = "",
    TypeParameter = "",
    Variable = "",

    Unknown = "",
    Keyword = "",
    Text = "",
    Unit = "",
    Value = "",
    Snippet = "",
    Color = "",
    Reference = "",
    Folder = "",
  },
  type = {
    Array = " ",
    Boolean = " ",
    Number = " ",
    String = " ",
    Object = " ",
  },
  bufferline = {
    indicator = "▎",
    buffer_close = "",
    modified = "●",
    tab_close = "",
    truncate_left = "",
    truncate_right = "",
  },
  diagnostics = {
    error = "",
    warn = "",
    hint = "",
    info = "",
    lightbulb = "",
    inv_error = "",
    inv_warn = "",
    inv_lightbulb = "",
    inv_hint = "",
  },
  gitsigns = {
    add = "▌",
    change = "▌",
    delete = "契",
    topdelete = "契",
    changedelete = "▌",
  },
  indentline = {
    char = "│",
    context_char = "┃",
  },
  comments = {
    todo = " ",
    hack = " ",
    warn = " ",
    perf = " ",
    note = " ",
    fix = " ",
  }
}
