[settings]
experimental = true
disable_hints = ["registry"]

[tools]
usage = "latest"
node = "latest"
neovim = "latest"
go = "latest"
maven = "latest"
pnpm = "latest"
rust = "latest"
yarn = "latest"
java = "openjdk-22.0.2"
cheat = "latest"
poetry = "latest"
tmux = "3.4"
cmake = "latest"
bun = "latest"
kubectl = "latest"
kubectl-convert = "latest"

[env]
