#!/usr/bin/env bash

hyprpm purge-cache
hyprpm update

yes | hyprpm add https://github.com/Duckonaut/split-monitor-workspaces
hyprpm enable split-monitor-workspaces

yes | hyprpm add https://github.com/outfoxxed/hy3
hyprpm enable hy3

hyprpm reload
