#!/bin/bash

choice=$(<<EOF sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' -e '/^$/d' | rofi -dmenu --width=200 --height=200
  suspend
  suspend-lock
  shutdown
  reboot
  lock
  hibernate
  hibernate-lock
EOF)

case "$choice" in
  hibernate-lock) hyprlock & systemctl hibernate ;;
  hibernate) systemctl hibernate ;;
  lock) hyprlock & ;;
  reboot) systemctl reboot ;;
  shutdown) systemctl poweroff ;;
  suspend-lock) hyprlock & systemctl suspend ;;
  suspend) systemctl suspend ;;
esac
