#!/bin/bash

choice=$(echo -e "hibernate\nhibernate-lock\nsuspend\nsuspend-lock\nsleep\nsleep-lock\nshutdown\nreboot\nlock" | rofi -dmenu --width=200 --height=200 )

case "$choice" in
  hibernate) systemctl hibernate ;;
  hibernate-lock) hyprlock & systemctl hibernate ;;
  suspend) systemctl suspend ;;
  suspend-lock) hyprlock & systemctl suspend ;;
  sleep) systemctl sleep ;;
  sleep-lock) hyprlock & systemctl sleep ;;
  shutdown) systemctl poweroff ;;
  reboot) systemctl reboot ;;
  lock) hyprlock & ;;
esac
