#!/bin/bash
file=`readlink -f ${@: -1}`
args="${@:1:$#-1}"
dir=`dirname $file`
command="bat -pp $args $file"

# inotifywait processes won't get killed
clear
if [[ ! -f "$file" ]]; then
  echo "File '$file' does not exist. Waiting for creation..."
  inotifywait -e create,moved_to --include $file --format "%w%f %e" -q -q $dir
  clear
else
  eval $command
fi
while read changed; do
  clear
  if [ $changed = MOVE_SELF ]; then
    echo "File '$file' was moved."
    break
  elif [ $changed = DELETE_SELF ]; then
    echo "File '$file' was deleted."
    break
  fi
  eval $command
done < <(inotifywait -m -e close_write,delete_self,move_self --format "%e" -q $file)
