#!/bin/bash

file=`pwd`/$1
dir=`dirname $file`

clear
if [[ ! -f "$file" ]]; then
  echo "File '$file' does not exist. Waiting for creation..."
  inotifywait -e create,moved_to --include $1 --format "%w%f %e" -q -q $dir
  clear
fi
while read changed; do
  clear
  if [ $changed = MOVE_SELF ]; then
    echo "File '$file' was moved."
    break
  elif [ $changed = DELETE_SELF ]; then
    echo "File '$file' was deleted."
    break
  fi
  bat -pp $file
done < <(inotifywait -m -e close_write,delete_self,move_self --format "%e" $1)
