#!/usr/bin/env bash

# Example:
# ./git-merge-tree tpo-lab1 git@github.com:klephron/repository.git \
# main subdir

set -u # Don't allow executing with empty variable
set -e # Exit when command fails

remote_name=$1
remote_url=$2
remote_branch=$3
repo_prefix=$4

prev_branch=$(git rev-parse --abbrev-ref HEAD)

(set -x;
  git remote add $remote_name $remote_url
  git fetch $remote_name $remote_branch

  git switch -c merge-$remote_name
  git merge -s ours --no-commit --allow-unrelated-histories $remote_name/$remote_branch
  git read-tree --prefix=$repo_prefix -u $remote_name/$remote_branch
  git commit -m "Merge $remote_name/$remote_branch as subdir"

  # git pull -s subtree $remote_name $remote_branch

  git checkout $prev_branch
)

echo "----------(Manually rebase merge-$remote_name)----------"
echo "git rebase merge-$remote_name"
echo "git branch -D merge-$remote_name"
echo "git remote remove $remote_name"
