require "user.utils.globals"
require "user.settings"
require "user.keymaps"
require "user.colorscheme"
require "user.plugins"
require "user.autocmds"
require "user.watch"
-- SERVERS: "user.plugins.lsp.lsp_installer"
