-- Nerd Font Icons
-- codicons (vscode)
local type_1 = {
  kind = {
    Text = "",
    -- Method = "m",
    -- Function = "",
    -- Constructor = "",
    Method = "",
    Function = "",
    Constructor = "",
    Field = "",
    -- Variable = "",
    Variable = "",
    Class = "",
    Interface = "",
    -- Module = "",
    Module = "",
    Property = "",
    Unit = "",
    Value = "",
    Enum = "",
    -- Keyword = "",
    Keyword = "",
    -- Snippet = "",
    Snippet = "",
    Color = "",
    File = "",
    Folder = "",
    EnumMember = "",
    Constant = "",
    Struct = "",
    Event = "",
    Operator = "",
    TypeParameter = "",
  },
  type = {
    Number = "",
    String = "",
    Boolean = "蘒",
    Object = "",
  },
  documents = {
    File = "",
    Files = "",
    Folder = "",
    OpenFolder = "",
  },
  git = {
    Add = "",
    Mod = "",
    Remove = "",
    Ignore = "",
    Rename = "",
    Diff = "",
    Repo = "",
  },
  ui = {
    ArrowClosed = "",
    ArrowOpen = "",
    Lock = "",
    Circle = "",
    BigCircle = "",
    BigUnfilledCircle = "",
    Close = "",
    Search = "",
    Lightbulb = "",
    Project = "",
    Dashboard = "",
    History = "",
    Comment = "",
    Bug = "",
    Code = "",
    Gear = "",
    Package = "",
    List = "",
    SignOut = "",
    Check = "",
    Fire = "",
    Note = "",
    BookMark = "",
    Pencil = "",
    -- ChevronRight = "",
    ChevronRight = ">",
    Table = "",
    Calendar = "",
    CloudDownload = "",
  },
  diagnostics = {
    Error = "",
    Warning = "",
    Information = "",
    Question = "",
    Hint = "",
  },
  misc = {
    Robot = "ﮧ",
    Squirrel = "",
    Tag = "",
    Watch = "",
  },
}

--   פּ ﯟ   蘒練 some other good icons
local type_2 = {
  kind = {
    Array = " ",
    Boolean = " ",
    Text = " ",
    Method = " ",
    Function = " ",
    Constructor = " ",
    Field = " ",
    Variable = " ",
    Class = " ",
    Interface = " ",
    Module = " ",
    Property = " ",
    Unit = " ",
    Value = " ",
    Enum = " ",
    Keyword = " ",
    Snippet = " ",
    Color = " ",
    File = " ",
    Reference = " ",
    Folder = " ",
    EnumMember = " ",
    Constant = " ",
    Struct = " ",
    Event = " ",
    Operator = " ",
    TypeParameter = " ",
    Misc = " ",
  },
  type = {
    Array = " ",
    Boolean = " ",
    Number = " ",
    String = " ",
    Object = " ",
  },
  documents = {
    File = " ",
    Files = " ",
    Folder = " ",
    OpenFolder = " ",
  },
  git = {
    Add = " ",
    Mod = " ",
    Remove = " ",
    Ignore = " ",
    Rename = " ",
    Diff = " ",
    Repo = " ",
  },
  ui = {
    ArrowClosed = "",
    ArrowOpen = "",
    Lock = " ",
    Circle = " ",
    BigCircle = " ",
    BigUnfilledCircle = " ",
    Close = " ",
    Search = " ",
    Lightbulb = " ",
    NewFile = " ",
    Project = " ",
    Dashboard = " ",
    History = " ",
    Comment = " ",
    Bug = " ",
    Code = " ",
    Gear = " ",
    Package = " ",
    List = " ",
    SignIn = " ",
    SignOut = " ",
    NoteBook = " ",
    Check = " ",
    Fire = " ",
    Note = " ",
    BookMark = " ",
    Pencil = " ",
    ChevronRight = "",
    Table = " ",
    Calendar = " ",
    CloudDownload = " ",
  },
  diagnostics = {
    Error = " ",
    Warning = " ",
    Information = " ",
    Question = " ",
    Hint = " ",
  },
  misc = {
    Robot = " ",
    Squirrel = " ",
    Tag = " ",
    Watch = " ",
  },
}

return {
  alpha = {
    File = "",
    FindFile = "",
    Folder = "",
    Settings = "",
    RecentlyUsed = "",
    Quit = "",
    Text = "",
    Telescope = "",
    SignIn = "",
    Reference = "",
    Checkhealth = "",
  },
  Close = " ",
  Telescope = " ",
  --   פּ ﯟ   some other good icons
  -- find more here: https://www.nerdfonts.com/cheat-sheet
  kind_icons = {
    Array = " ",
    Boolean = " ",
    Class = "",
    Constant = "",
    Constructor = "",
    Enum = "",
    EnumMember = "",
    Event = "",
    Field = "",
    File = "",
    Function = "",
    Interface = "",
    Key = "",
    Method = "m",
    Module = "",
    Namespace = "ﰩ",
    Null = "n",
    Number = " ",
    Object = " ",
    Operator = "",
    Package = "",
    Property = "",
    String = " ",
    Struct = "",
    TypeParameter = "",
    Variable = "",

    Unknown = "",
    Keyword = "",
    Text = "",
    Unit = "",
    Value = "",
    Snippet = "",
    Color = "",
    Reference = "",
    Folder = "",
  },
  type = {
    Array = " ",
    Boolean = " ",
    Number = " ",
    String = " ",
    Object = " ",
  },
  bufferline = {
    indicator = "▎",
    buffer_close = "",
    modified = "●",
    tab_close = "",
    truncate_left = "",
    truncate_right = "",
  },
  diagnostics = {
    error = "",
    warn = "",
    hint = "",
    info = "",
    lightbulb = "",
    inv_error = "",
    inv_warn = "",
    inv_lightbulb = "",
    inv_hint = "",
  },
  gitsigns = {
    add = "▌",
    change = "▌",
    delete = "契",
    topdelete = "契",
    changedelete = "▌",
  },
  indentline = {
    char = "│",
    context_char = "┃",
  },
  comments = {
    todo = " ",
    hack = " ",
    warn = " ",
    perf = " ",
    note = " ",
    fix = " ",
  }
}
